name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  MD_APPLE_SDK_ROOT: /Applications/Xcode.app

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint --strict || true
    
    - name: Generate version
      run: just version
    
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
        xcode-select -p
    
    - name: List Schemes
      run: xcodebuild -list -project MemStat.xcodeproj || true
    
    - name: Build Debug
      run: |
        xcodebuild build \
          -project MemStat.xcodeproj \
          -target MemStat \
          -configuration Debug \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Run Tests
      run: just test
    
    - name: Build Release  
      run: |
        xcodebuild build \
          -project MemStat.xcodeproj \
          -target MemStat \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="-" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          build/Logs/Test/*.xcresult
          TestResults/
        retention-days: 30
    
    - name: Upload Debug Build
      uses: actions/upload-artifact@v4
      with:
        name: MemStat-Debug
        path: build/Build/Products/Debug/MemStat.app
        retention-days: 7
    
    - name: Upload Release Build
      uses: actions/upload-artifact@v4
      with:
        name: MemStat-Release
        path: build/Build/Products/Release/MemStat.app
        retention-days: 30