name: Release

on:
  push:
    tags:
      - 'v*'

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  MD_APPLE_SDK_ROOT: /Applications/Xcode.app

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install create-dmg
      run: brew install create-dmg
    
    - name: Import Code Signing Certificates
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    
    - name: Generate version
      run: ./Scripts/generate_version.sh
    
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
        xcode-select -p
    
    - name: Build Release
      run: |
        xcodebuild build \
          -project MemStat.xcodeproj \
          -scheme MemStat \
          -configuration Release \
          -derivedDataPath build \
          -sdk macosx
    
    - name: Code Sign Application
      env:
        CODESIGN_IDENTITY: ${{ secrets.CODESIGN_IDENTITY }}
      run: |
        ./Scripts/codesign_app.sh "build/Build/Products/Release/MemStat.app" "$CODESIGN_IDENTITY"
    
    - name: Notarize Application
      env:
        NOTARIZATION_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
        NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
        NOTARIZATION_TEAM_ID: ${{ secrets.NOTARIZATION_TEAM_ID }}
      run: |
        ./Scripts/notarize_app.sh \
          "build/Build/Products/Release/MemStat.app" \
          "$NOTARIZATION_USERNAME" \
          "$NOTARIZATION_PASSWORD" \
          "$NOTARIZATION_TEAM_ID"
    
    - name: Create DMG
      run: |
        ./Scripts/package_dmg_styled.sh \
          "build/Build/Products/Release/MemStat.app" \
          "MemStat-${{ github.ref_name }}.dmg"
    
    - name: Create ZIP
      run: |
        ./Scripts/package_zip.sh \
          "build/Build/Products/Release/MemStat.app" \
          "MemStat-${{ github.ref_name }}.zip"
    
    - name: List artifacts
      run: ls -la dist/ || true
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: MemStat ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          dist/*.dmg
          dist/*.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}